DATA:
  root_dir: "data/cifar-10-batches-py"
  img_size: 224

MODEL:
  HEAD:
    dim1: 512
    dim2: 128

TRAINING:
  batch_size: 64
  n_epochs: 100

LOSS:
  temperature: 0.5

LOGGING:
  logging_dir: "artifacts/logs"
  media_dir: "media"